### PR TITLE
New ignoreRequiredCheck flag making all properties optional, and new ability to serialize object using mappings from a specified class

### PR DESCRIPTION
**Pull request by cmolodo**
This is a great library overall!

However, I have a somewhat specific use case which the library doesn't currently match.  I have a large class with defined property mappings whose values are filled in through multiple Angular reactive forms.  The forms basically match the structure of the class, and include some values which are objects (like Dates), that I'd like to use my pre-defined mappings for.  However, there are 2 problems:

- The form output is not itself an instance of the mapped class, so doesn't have any defined property mappings.
- Because the object is filled in using multiple forms, the output may not include values for all the "required" fields that I expect when deserializing a full object.

To addresss this, I've added 2 features:

- New ignoreRequiredCheck flag which effectively makes all properties optional, even if the property mapping doesn't specify isOptional = true. (commit 3b34cc3)
- Added optional classReference parameters to all serialization methods, to allow serialization of an object using mappings from the specified class reference instead of mappings from the object itself. (commit c0591fd)

I've added/updated tests to include these new features, and added some test fixes/expansions as well.  (For example, if the current tests are run west of GMT, they'll fail because of the way the test DateConverter is implemented.)

Note that adding the new optional classReference parameters to the serialization methods means that the data object parameters must now accept "any" instead of the specific generic class instance.

### CODE REVIEW

**Comment by andreas-aeschlimann** [comment]
Thanks for your PR, I will look into it when I work on the library again.

Can you provide a minimal example of the problems you had?

If I understand correctly: 

1) You want to serialize an instance of any object using a given structure, for example:

```
@JsonObject("Cat")
class Cat {
    @JsonConvert("name", String) name: string = "";
}
```
and then `jsonConvert.serializeObject({"name": "Kitty"}, Cat)`, so you can basically validate the structure.

2) You want to be able to ignore all properties that are missing instead of throwing an error or manually inserting the "ignore" flag.

**Comment by cmolodo** [comment]
Thank you for the response!

For point 1, it's less about validation and more about using the mapping I've already created to generate a JSON object for transmission to the back end, so I don't have to duplicate that effort.

For example, I have some date-picker form fields that output a Date object as the value.  I want to keep the values as Date objects so I can work with them in the application more easily (e.g. for validation, etc).  However, I'll eventually need to send these values to the back end, and I'd like to be able to use the date converter mapping I've got on my class to convert all the Date properties to strings.

Hopefully that made sense?

For point 2, that's exactly right.

**Comment by cmolodo** [comment]
Also, I've just encountered a more general issue with the library, in the getClassPropertyMappingOptions() method.  

Because the "indirect" mapping simply searches by property name, and because all the mappings are just grouped into one array, if two unrelated classes have a property with the same name but different types, you may end up with an incorrect mapping.

Addtitionally, if you explicitly don't map the property on one class, but you do on the other, it will still end up getting serialized/deserialized, because the other mapping will be used!  For example, in the documentation example of the City class, it says the following:

```
@JsonObject("City")
class City {

    // This property has no @JsonProperty. 
    // It will not be mapped.
    id: number = 123;
```
However, if there were another class that *did* map an id property, the City.id value will be incorrectly serialized.

I assume the indirect mapping was put in place to handle inherited mapped properties?  I'm working on a fix to instead step up the prototype chain looking for parent mapped properties - so as long as the parent class with the property is also annotated as a `@JsonObject`, it should find the mapping.  I'll add the commit with the fix and some new tests to this pull request.

As an aside, if you think only one of these changes is useful, please let me know!  I'm happy to make a new branch/pull request with just that feature.  (Though I'll maintain my fork, since I need all of them.)

**Comment by cmolodo** [comment]
Actually, just to refine my earlier comment on property mapping conflicts: it'll only be an issue if the 2 classes with the same property name are in the same inheritance hierarchy.  

So, going back to City above, it would only be a problem if the other class shared a common parent with City, or if it was a subclass of City.  If the two classes aren't linked in any way, there won't be a conflict.

**Comment by cmolodo** [comment]
Closing this pull request in favor of https://github.com/AppVision-GmbH/json2typescript/pull/121 - I'll reopen with an updated branch once the above pull request is accepted.

**Pull request closed without merging**
