### PR TITLE
Add property with the same name on different classes

### PR DESCRIPTION
**Pull request by tobiasschweizer**
I am trying to reproduce a problem I have here: https://github.com/dasch-swiss/knora-api-js-lib/pull/86#discussion_r341854586

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
@andreas-aeschlimann 

https://github.com/AppVision-GmbH/json2typescript/blob/ab750a0815c5f0e3792d0d823287826aa0b889e8/src/json2typescript/json-convert.ts#L704-L708

`indirectMappingNames` contains all mappings for the given `propertyName` but this should only by super classes of the class we are looking at.

**Comment by tobiasschweizer** [comment]
@andreas-aeschlimann If you run `npm test` you will see the following output:

> LOG: 'name', 'SmallCat.name', ['Animal.name', 'Kitty.name']

The first indirect mapping for `name` is taken from `Animal`, but it should come from `Cat` (Kitty). I am facing a situation where indirect mappings contain information from classes that are not even super classes of the class I am looking at.

**Comment by tobiasschweizer** [comment]
@andreas-aeschlimann Can you confirm if that's a bug?

**Comment by tobiasschweizer** [comment]
This is kind of an urgent issue for me because currently I have to limit class inheritance to avoid having this problem. If I am doing something wrong, I would be glad if you pointed it out to me.

**Comment by andreas-aeschlimann** [comment]
I'll look into it when I have time. Sorry this is still on hold.

**Comment by cmolodo** [comment]
@tobiasschweizer I ran into this also, and fixed it on my fork.  However, the fix is included with a new feature in [this PR](https://github.com/AppVision-GmbH/json2typescript/pull/92), you may not want the whole thing?  I can pull it out into a separate branch if you just want the current json2typescript with the fix for class inheritance-based mapping.

**Comment by andreas-aeschlimann** [comment]
Sorry for being so late, I should have looked into this some time ago. I did not bump into your issues yet, so I will have to study your comments in depth.

I will resolve the open pull requests until the end of February and come back to you.

@cmolodo are the issues of @tobiasschweizer fixed in your PR?

**Comment by cmolodo** [comment]
@andreas-aeschlimann I believe so - I ran into a similar issue with conflicts over classes having the same property name even if they weren't in direct inheritance, and modified the method he highlights to instead step up the inheritance hierarchy via Object.getPrototypeOf().  But I don't know if you want to pull all the rest of my changes as well?  I'm creating a new branch with only the fix, I'll submit a separate PR for that and clean up my original.

**Comment by cmolodo** [comment]
@andreas-aeschlimann PR in with just the fix plus tests, if you want it: [PR 121](https://github.com/AppVision-GmbH/json2typescript/pull/121)

**Comment by andreas-aeschlimann** [comment]
Thanks, I'll be on it next week.

**Comment by tobiasschweizer** [comment]
> I believe so - I ran into a similar issue with conflicts over classes having the same property name even if they weren't in direct inheritance, and modified the method he highlights to instead step up the inheritance hierarchy via Object.getPrototypeOf(). 

@cmolodo Great that you can confirm this, I was not sure if I was doing something wrong. I did not only experience a problem with **indirect** inheritance, but also with cases like this

```
  A
 /  \ 
B    C
```

Properties of A, B and C ended all up in a global connection also if there was not hierarchical relation like in the case of B and C. B and C should solely get properties from A. 

I applied a workaround (limiting my inheritance) so the issue does not occur at the moment but I would very much like to work with a new version of json2typescript that includes your fix.

Does #121 include tests for the case illustrated above (sibling classes)?

**Comment by cmolodo** [comment]
@tobiasschweizer Yes - sibling classes with the same property name is exactly the issue I ran into, and is what I set up the tests for.  In the tests I added a new DuplicateCat class that extends Animal and which has the same property name as Cat, which also extends Animal.  

Although I've just realized I didn't test completely - I checked that the duplicate property was correctly **not** serialized (because that was my problem), but I didn't check that it would be correctly serialized.  I'll fix that now.

I'll note that the property mappings are technically all still in a global collection, but now they're retrieved through prototype inheritance rather than just by property name, so it only finds the properties that belong to the class.

**Comment by cmolodo** [comment]
Okay, I've updated the tests to also check a mapped property with duplicate name.

**Comment by tobiasschweizer** [comment]
That’s great, thank you. I will try to have a look at it next week.

**Comment by andreas-aeschlimann** [comment]
Can we close #116 in favor of #121?

**Comment by andreas-aeschlimann** [comment]
Closed as discussed per SMS.

**Pull request closed without merging**
